### ISSUE TITLE
Tasks editing

### ISSUE THREAD

**Issue by YoHidden** [ph4r05/javacard-gradle-template#11]
Hi there,

Is there a way to edit the contents of the tasks, like _buildJavaCard_ or _installJavaCard_ ? I have tried by editing run configurations but the _VM options_ and _Arguments_ have nothing to do with it.
I don't even know where are these tasks file located.
Thanks.

**Comment by ph4r05** [comment]
Hi @YoHidden, it is not possible to edit the task directly. Tasks are provided by the [javacard-gradle-plugin](https://github.com/ph4r05/javacard-gradle-plugin) so in order to change them you would have to fork the plugin, do the changes, install it locally and use in your project instead of the upstream version.

But it should be possible to do what you want without modifying the plugin code. Maybe add another gradle task that calls buildJavaCard? Some things can be also configured. What do you want to achieve?

**Comment by ph4r05** [comment]
If it is absolutely necessary to edit the tasks and it makes sense to support such an extension globally, you can try to fork the plugin and do the pull request. If it is good and makes sense I can merge it.

**Comment by YoHidden** [comment]
Thanks @ph4r05 . My intention was simply to add some parameters to the underlying call to he GlobalPlatform tool. For example, to address exactly to the card reader, or to pass some install parameters to the applet. Or whatever any other command line option available fro the gp.exe tool.
In any case, I can do that manually by calling gp.exe from the command line. So I think it is not worth to take the fork process.
Thanks anyway.

**Comment by ph4r05** [comment]
Ah that makes sense, I can think about extending it and let you know. buildJavaCard does not interact with the gp, just ant-javacard, so it should not be needed. 

You can also define custom gradle tasks calling GP

```gradle
    task deleteApplet(type: fr.bmartel.javacard.gp.GpExec) {
        description = 'Delete applet'
        group = 'global platform'
        args (['-d', '--delete', '00000000000000'] + gpKeyArgs())
    }

    task gp(type: fr.bmartel.javacard.gp.GpExec) {
        description = 'General GP command'
        group = 'global platform'
        if (project.hasProperty("gpArgs")){
            //logger.println("Use -PgpArgs=\"-d,--list\"")
            args "$gpArgs".split(",")
        }
    }

    task gpRenameAppletManager(type: fr.bmartel.javacard.gp.GpExec) {
        description = 'Changes AID of the applet manager to one usable on mobile platforms'
        group = 'global platform'
        def mgrAid = project.hasProperty("aid") ? "$aid" : cfg.appletManagerAid
        args (['-d', '-rename-isd', "$mgrAid"] + gpKeyArgs())
    }
```

**Comment by YoHidden** [comment]
Ok, that looks fine. I'll try it. Thanks a lot.

**Comment by ph4r05** [comment]
The new version now supports `installGpProArgs` arguments in the `config` level.

```
config {
    installGpProArgs '-d'
    installGpProArgs '--another-param`
}
```
