### ISSUE TITLE
test apdu response in secure channel 

### ISSUE THREAD

**Issue by iampkuhz** [ph4r05/javacard-gradle-template#3]
Hi, I'm a beginner in javacard and I want to test an apdu response for an applet following this repo.

My applet is almost the same as https://stackoverflow.com/a/30839366, And I want to makeup a test for this store instruction.

My question is, how can I open the secure channel and transmit my apdu in the secure chanell in my AppletTest.java?

thanks for your help!

**Comment by petrs** [comment]
Hi, 
glad to see more and more people getting interested in the JavaCard developement. The applet you have contains only on-card part (which implements secure channel SCP), but you need also pc-side application implementating this secure channel (and sending STORE_DATA apdu). Take a look at https://github.com/martinpaljak/GlobalPlatformPro - this tool implements SCP and manages applets on a card.

**Comment by iampkuhz** [comment]
thanks for your reply~

As I see, your test code(AppletTest.java, SimpleAPDU) is run by the javacard-tools jar dependency. It's a SE simulation environment? just like GPPro?
In further, I can't add some simple code to meet my needs by this?:

```
public class AppletTestGithubIssue {

    // 0504030201 is the secure data
    private static final String APDU_1_W_SecData = "00B00000050504030201";

    @BeforeClass
    public static void setUpClass() throws Exception {
        SimpleAPDU.initENV();
    }

    @Test
    public void testSecureData() throws Exception {
        // TODO
        // some code to open the secure channel ??
        //
        ResponseAPDU apdu = SimpleAPDU.demoSingleCommand(APDU_1_W_SecData);
        Assert.assertNotNull(apdu);
        Assert.assertEquals(0x9000, apdu.getSW());
    }
}
```

BTW, would this be possible?
```
 @Test
    public void testSecureData() throws Exception {
        // TODO
        // some code to open the secure channel ??
        GPSystem.xxxxx
        //
        ResponseAPDU apdu = SimpleAPDU.demoSingleCommand(APDU_1_W_SecData);
        Assert.assertNotNull(apdu);
        Assert.assertEquals(0x9000, apdu.getSW());
    }

```

**Comment by petrs** [comment]
We use jcardsim.org for simulation of on-card functionality. The jcardsim in free version do not have support for GPSystem, but I believe they have this part available for fee: https://jcardsim.org/blogs/jcardsim-gp-global-platform-module-jcardsim

Other option is to extract relevant code directly from GlobalPlatformPro

**Comment by iampkuhz** [comment]
got it, thanks a lot!
