### ISSUE TITLE
compiled cap throw non-expected SW

### ISSUE THREAD

**Issue by iampkuhz** [ph4r05/javacard-gradle-template#4]
hi, I've been developing applet based on this project.

However, I found the cap build tools cause error.
In my case, I found that the target cap throw 0x6982 apdu SW while we expected another customized SW code (0x63??). this error disappeared when I comment transaction project among the code block.
I'm pretty sure it's the compiler error instead of my code. I setup a eclipse+jcde development environment (in Windows) and compile .cap file from exact the same code, I got the expected SW code (0x63??). Sorry for not possible to show the source code.

BTW, it's great project for developing and cause no problem for most of the code/test.

What's the compile extension/tools? any update？

**Comment by ph4r05** [comment]
Hi! thanks for the comment. This is interesting, we use tools provided by Martin Paljak 
https://github.com/martinpaljak

Namely https://github.com/martinpaljak/ant-javacard and https://github.com/martinpaljak/oracle_javacard_sdks

Pls try another javacard SDK version if that causes the same problem. I can try to update dependencies.

I am glad you find this project helpful! :)

**Comment by ph4r05** [comment]
Btw - it might be you compile CAP with new SDK version - newer than your card supports.

**Comment by iampkuhz** [comment]
jcdk version is not the cause. If I use a newer version, cap could not be downloaded to SE. I also tried older version but the problem remains.

**Comment by iampkuhz** [comment]
yes， in my case, the se card support jc3.0.3, and i also use that verson of sdk to compile. BTW, if using jc2.2.2 to compile, the generate cap could also be downloaded into se card. if using jc3.0.5 to compile, the cap file could not be downloaded.

in my case, the downloading process has no problem~

**Comment by ph4r05** [comment]
re-open if problem reoccurs
