### ISSUE TITLE
how to setup IntelliJ?

### ISSUE THREAD

**Issue by johnnytshi** [ph4r05/javacard-gradle-template#6]
Hi,

New here, I have 2 questions:

1. Has anyone set it up in IntelliJ? Can you share the step?

2. How to switch the test to run on physical card?

All the best!

Johnny

**Comment by ph4r05** [comment]
ad 1. The gradle project can be opened in Idea. I’ve done that.

**Comment by johnnytshi** [comment]
thanks...just figured out the coverage stuff

on to question 2, do you know how to run test with physical card?

**Comment by johnnytshi** [comment]
nvm

FYI, uncomment this inside SimpleAPDU:

runCfg.setTestCardType(RunConfig.CARD_TYPE.PHYSICAL);
