### ISSUE TITLE
Nice message - location of libpcsclite.so on Linux

### ISSUE THREAD

**Issue by lzaoral** [ph4r05/javacard-gradle-template#9]
JDK has got a built-in path to this library. However, some Linux distributions (e.g. Ubuntu) use a completely different one and connection to smart card reader then fails regardless of its presence. 

It would be nice to inform the users with a friendly message, when this occurs. Additional info can be found on https://stackoverflow.com/questions/12376257/accessing-javax-smartcardio-from-linux-64-bits or https://bugs.launchpad.net/ubuntu/+source/openjdk-7/+bug/898689.

**Comment by ph4r05** [comment]
I've solved this issue by using apdu4j card channel by default. It handles similar problems. Also `javax.smartcardio` is not working anymore on OSX BigSur.
